from deep_translator import GoogleTranslator

# Initialize the translator
translator = GoogleTranslator(source="ko", target="en")
import json

name_mapping = {
  "늑대": "Wolf",
  "대륙사슴": "Manchurian Sika Deer",
  "반달가슴곰": "Asiatic Black Bear",
  "붉은박쥐": "Red bat",
  "사향노루": "Siberian Musk Deer",
  "산양": "Long-tailed Goral",
  "수달": "Eurasian Otter",
  "스라소니": "Eurasian Lynx",
  "여우": "Red Fox",
  "작은관코박쥐": "Ussuri tube-nosed bat",
  "표범": "Amur Leopard",
  "호랑이": "Amur Tiger",
  "담비": "Yellow-throated marten",
  "무산쇠족제비": "Least Weasel",
  "물개": "Northern Fur Seal",
  "물범": "Spotted seal",
  "삵": "Leopard cat",
  "큰바다사자": "Steller Sea Lion",
  "토끼박쥐": "Ognev's long-eared bat",
  "하늘다람쥐": "Siberian Flying Squirrel",
  "검독수리": "Golden Eagle",
  "넓적부리도요": "Spoon-billed Sandpiper",
  "노랑부리백로": "Chinese Egret",
  "두루미": "Red-crowned crane",
  "매": "Peregrine Falcon",
  "먹황새": "Black Stork",
  "저어새": "Black-faced Spoonbill",
  "참수리": "Steller's sea eagle",
  "청다리도요사촌": "Nordmann's Greenshank",
  "크낙새": "White-bellied Woodpecker",
  "호사비오리": "Scaly-sided merganser",
  "혹고니": "Mute Swan",
  "황새": "Oriental Stork",
  "흰꼬리수리": "White-tailed Eagle",
  "개리": "Swan Goose",
  "검은머리갈매기": "Saunders's Gull",
  "검은머리물떼새": "Eurasian Oystercatcher",
  "검은머리촉새": "Yellow-breasted Bunting",
  "검은목두루미": "Common Crane",
  "고니": "Tundra Swan",
  "고대갈매기": "Relict Gull",
  "긴꼬리딱새": "Japanese Paradise Flycatcher",
  "긴점박이올빼미": "Ural Owl",
  "까막딱다구리": "Black Woodpecker",
  "노랑부리저어새": "Eurasian Spoonbill",
  "느시": "Great Bustard",
  "독수리": "Cinereous Vulture",
  "따오기": "Crested Ibis",
  "뜸부기": "Watercock",
  "무당새": "Yellow Bunting",
  "물수리": "Osprey",
  "벌매": "Crested Honey Buzzard",
  "붉은배새매": "Chinese Sparrowhawk",
  "붉은어깨도요": "Great Knot",
  "붉은해오라기": "Japanese Night Heron",
  "뿔쇠오리": "Japanese Murrelet",
  "뿔종다리": "Crested Lark",
  "새매": "Eurasian Sparrowhawk",
  "새호리기": "Eurasian Hobby",
  "섬개개비": "Pleske's Grasshopper Warbler",
  "솔개": "Black Kite",
  "쇠검은머리쑥새": "Ochre-rumped Bunting",
  "수리부엉이": "Eurasian Eagle-Owl",
  "알락개구리매": "Pied Harrier",
  "알락꼬리마도요": "Far Eastern Curlew",
  "양비둘기": "Eastern Rock Dove",
  "팔색조": "Fairy pitta",
  "재두루미": "White-naped Crane",
  "잿빛개구리매": "Hen Harrier",
  "조롱이": "Japanese Sparrowhawk",
  "참매": "Northern Goshawk",
  "큰고니": "Whooper Swan",
  "큰기러기": "Bean Goose",
  "큰덤불해오라기": "Schrenck's Bittern",
  "큰말똥가리": "Upland Buzzard",
  "올빼미": "Tawny Owl",
  "항라머리검독수리": "Greater Spotted Eagle",
  "흑기러기": "Brant Goose",
  "흑두루미": "Hooded Crane",
  "흑비둘기": "Japanese Wood Pigeon",
  "흰목물떼새": "Long-billed Plover",
  "흰이마기러기": "Lesser White-fronted Goose",
  "흰죽지수리": "Eastern Imperial Eagle",
  "비바리뱀": "Bibar's keelback",
  "구렁이": "Korean Rat Snake",
  "남생이": "Reeves' Turtle",
  "표범장지뱀": "Mongolia racerunner",
  "수원청개구리": "Suweon treefrog",
  "고리도롱뇽": "Kori salamander",
  "금개구리": "Seoul frog",
  "맹꽁이": "Narrow-mouth frog",
  "감돌고기": "Black shinner",
  "꼬치동자개": "Korean stumpy bullhead",
  "남방동사리": "Dark sleeper",
  "모래주사": "Korean Sand Goby",
  "미호종개": "Miho Spine Loach",
  "얼룩새코미꾸리": "Spotted Naktong Loach",
  "여울마자": "Rapid gudgeon",
  "임실납자루": "Imshil Bitterling",
  "좀수수치": "Dwarf loach",
  "퉁사리": "Bull-head torrent catfish",
  "흰수마자": "Nakdong Gudgeon",
  "가는돌고기": "Slender shinner",
  "가시고기": "Three-spined Stickleback",
  "꺽저기": "Japanese perch",
  "꾸구리": "Big-headed Gobiobotia",
  "다묵장어": "Far Eastern brook lamprey",
  "돌상어": "Stone Shark",
  "묵납자루": "Striped Bitterling",
  "버들가지": "Willow Minnow",
  "부안종개": "Puan spine loach",
  "연준모치": "Common Minnow",
  "열목어": "Manchurian Lenok",
  "칠성장어": "Japanese river lamprey",
  "큰줄납자루": "Large-banded Bitterling",
  "한강납줄개": "Hangang bitterling",
  "한둑중개": "Korean Sculpin",
  "붉은점모시나비": "Red-Spotted Apollo Butterfly",
  "비단벌레": "Korean Jewel Beetle",
  "산굴뚝나비": "Mountain Brown",
  "상제나비": "Black-veined White",
  "수염풍뎅이": "Manchurian Cockchafer",
  "장수하늘소": "longhorn beetle",
  "깊은산부전나비": "Large Copper",
  "한국꼬마잠자리": "Korean Dragonfly",
  "노란잔산잠자리": "Japanese Golden-ringed Dragonfly",
  "닻무늬길앞잡이": "Anchor-patterned Tiger Beetle",
  "대모잠자리": "Angel Dragonfly",
  "두점박이사슴벌레": "Two-spotted Stag Beetle",
  "뚱보주름메뚜기": "Chubby Wrinkled Grasshopper",
  "멋조롱박딱정벌레": "Wonderful Ground Beetle",
  "물방개": "Oriental Water Beetle",
  "물장군": "Giant Water Bug",
  "소똥구리": "Dung Beetle",
  "쌍꼬리부전나비": "Takanonis Hairstreak",
  "애기뿔소똥구리": "Little Horned Dung Beetle",
  "여름어리표범나비": "Summer heath fritillary",
  "왕은점표범나비": "Great Silverstripe",
  "은줄팔랑나비": "Unicolorous Swift",
  "참호박뒤영벌": "Korean Bumblebee",
  "창언조롱박딱정벌레": "Chang-eon's Ground Beetle",
  "큰자색호랑꽃무지": "Large Purple Flower Chafer",
  "큰홍띠점박이푸른부전나비": "Great Scarlet-banded Blue",
  "귀이빨대칭이": "Cockscomb pearl mussel",
  "나팔고둥": "Pacific Triton",
  "남방방게": "Southern Fiddler Crab",
  "두드럭조개": "Knobbed Pond Mussel",
  "갯게": "Mud Crab",
  "거제외줄달팽이": "Geoje Land Snail",
  "검붉은수지맨드라미": "Blackish-red Soft Coral",
  "금빛나팔돌산호": "Golden Trumpet Coral",
  "기수갈고둥": "freshwater and brackish water snail",
  "깃산호": "Feather Coral",
  "대추귀고둥": "Date Ear Snail",
  "둔한진총산호": "Blunt Gorgonian Coral",
  "망상맵시산호": "Reticulated Gorgonian Coral",
  "물거미": "Water Spider",
  "밤수지맨드라미": "Chestnut Soft Coral",
  "별혹산호": "Star-wart Coral",
  "붉은발말똥게": "Red-footed Marsh Crab",
  "선침거미불가사리": "Spiny Brittle Star",
  "연수지맨드라미": "Soft Soft Coral",
  "염주알다슬기": "Beaded River Snail",
  "울릉도달팽이": "Ulleungdo Snail",
  "유착나무돌산호": "Adnate Tree Coral",
  "의염통성게": "False Heart Urchin",
  "자색수지맨드라미": "Purple Soft Coral",
  "잔가지나무돌산호": "Branched Tree Coral",
  "착생깃산호": "Epiphytic Feather Coral",
  "참달팽이": "Korean Land Snail",
  "측맵시산호": "Side Gorgonian Coral",
  "칼세오리옆새우": "Calceolaria Amphipod",
  "해송": "Sea Pine",
  "흰발농게": "White-legged Fiddler Crab",
  "흰수지맨드라미": "White Soft Coral",
  "광릉요강꽃": "Korean Lady's Slipper",
  "금자란": "Golden Orchid",
  "나도풍란": "False Wind Orchid",
  "만년콩": "Perennial Bean",
  "비자란": "East Asian thrixspermum",
  "암매": "Stone Heath",
  "죽백란": "Bamboo Orchid",
  "털복주머니란": "Hairy Lady's Slipper Orchid",
  "풍란": "Wind Orchid",
  "한라솜다리": "Korean edelweiss",
  "한란": "Cold Orchid",
  "가는동자꽃": "Slender Lychnis",
  "가시연": "Prickly Waterlily",
  "가시오갈피나무": "Siberian Ginseng",
  "각시수련": "Dwarf Waterlily",
  "개가시나무": "Dog Oak",
  "갯봄맞이꽃": "Sea Milkwort",
  "검은별고사리": "Black Star Fern",
  "구름병아리난초": "Cloud Chick Orchid",
  "기생꽃": "Parasitic Flower",
  "끈끈이귀개": "Sticky Sundew",
  "나도승마": "Korean waxbells",
  "날개하늘나리": "Winged Sky Lily",
  "넓은잎제비꽃": "Broad-leaved Violet",
  "노랑만병초": "Yellow Rhododendron",
  "노랑붓꽃": "Dwarf woodland Korean iris",
  "단양쑥부쟁이": "Danyang Aster",
  "대성쓴풀": "Daeseong Bitter Grass",
  "대청부채": "Daecheong Fan Iris",
  "대흥란": "Daeheung Orchid",
  "독미나리": "Water Hemlock",
  "두잎약난초": "Two-leaved Medicinal Orchid",
  "매화마름": "Plum Blossom Water-crowfoot",
  "무주나무": "Muju Tree",
  "물고사리": "Water Fern",
  "방울난초": "Bell Orchid",
  "백부자": "White Aconite",
  "백양더부살이": "Baegyang Broomrape",
  "백운란": "Baegun Orchid",
  "복주머니란": "Korean lady's slipper",
  "분홍장구채": "Pink Silene",
  "산분꽃나무": "Mountain Viburnum",
  "산작약": "Mountain Peony",
  "삼백초": "Houttuynia",
  "새깃아재비": "Bird Feather Fern",
  "서울개발나물": "Seoul Angelica",
  "석곡": "Rock Orchid",
  "선제비꽃": "Line Violet",
  "섬개야광나무": "Island Cotoneaster",
  "섬현삼": "Island Figwort",
  "섬시호": "Island Bupleurum",
  "세뿔투구꽃": "Three-horned Aconite",
  "손바닥난초": "Palm Orchid",
  "솔잎난": "Pine Needle Orchid",
  "순채": "Water Shield",
  "신안새우난초": "Sinan Calanthe",
  "애기송이풀": "Baby Pedicularis",
  "연잎꿩의다리": "Lotus-leaved Meadow Rue",
  "왕제비꽃": "King Violet",
  "으름난초": "Akebia Orchid",
  "자주땅귀개": "Purple Bladderwort",
  "전주물꼬리풀": "Jeonju Water-tail Grass",
  "정향풀": "Clove Grass",
  "제비동자꽃": "Swallow Lychnis",
  "제비붓꽃": "Swallow Iris",
  "제주고사리삼": "Jeju Adder's Tongue Fern",
  "조름나물": "Buckbean",
  "죽절초": "Jointed-stem Bamboo",
  "지네발란": "Centipede Orchid",
  "진노랑상사화": "Deep Yellow Spider Lily",
  "차걸이란": "Tea Hang Orchid",
  "참닻꽃": "True Halenia",
  "참물부추": "True Water Chive",
  "초령목": "Early Bloomer Tree",
  "칠보치마": "Chilbo Skirt",
  "콩짜개란": "Bean Orchid",
  "큰바늘꽃": "Large Willowherb",
  "탐라란": "Tamra gastrochilus",
  "파초일엽": "Bird's Nest Fern",
  "피뿌리풀": "Bloodroot",
  "한라송이풀": "Hallasan Lousewort",
  "한라옥잠난초": "Hallasan Twayblade",
  "해오라비난초": "Egret Flower Orchid",
  "혹난초": "Wart Orchid",
  "홍월귤": "Red Bearberry",
  "그물공말": "Green Bubble Algae",
  "삼나무말": "Cedar Kelp",
  "화경솔밭버섯": "Omphalotus guepiniiformis",
  "큰뒷부리도요": "Bar-tailed Godwit",
  "쇠제비갈매기": "Little Tern",
  "청호반새": "Black-capped Kingfisher",
  "붉은가슴흰죽지": "Baer's Pochard",
  "시베리아흰두루미": "Siberian Crane",
  "둑중개": "Korean Sculpin",
  "어름치": "Korean doty barbel",
  "새미": "Taczanowski's Minnow",
  "윤조롱박딱정벌레": "Yoon's Ground Beetle",
  "홍줄나비": "Red-striped Butterfly",
  "불나방": "Cream-spot Tiger Moth",
  "나도여로": "False Veratrum",
  "뿔제비갈매기": "Chinese Crested Tern",
  "눈썹고사리": "Eyebrow Spleenwort",
  "선모시대": "Erect Adenophora",
  "한라장구채": "Hallasan Silene",
  "나도범의귀": "False Saxifrage",
  "물석송": "Water Clubmoss",
  "장백제비꽃": "Jangbaek Violet"
}

def translate_name(korean, latin):
    return name_mapping.get(korean, latin)

# Helper function to translate actions and history
def translate_action_type(korean):
    mapping = {
        "해당없음": "Not Applicable",
        "최소관심(LC)": "Least Concern (LC)",
        "지역절멸(RE)": "Regionally Extinct (RE)",
        "천연기념물": "Natural Monument",
        "취약(VU)": "Vulnerable (VU)",
        "부속서Ⅰ": "Appendix I",
        "부속서Ⅱ": "Appendix II",
        "부속서Ⅲ": "Appendix III",
        "위기(EN)": "Endangered (EN)",
        "준위협(NT)": "Near Threatened (NT)",
        "위급(CR)": "Critically Endangered (CR)"
    }
    return mapping.get(korean, korean)

def translate(text):
    try:
        return translator.translate(text)
    except:
        print(text + ' is not translated.')
        return text

# Translate all extra_sections including their content
def translate_extra_sections_full(sections):
    title_map = {
        "형태": "Appearance",
        "생태": "Ecology",
        "위협요인": "Threats",
        "출처": "Source",
        "분포": "Distribution",
        "분류학적 위치": "Taxonomic Position",
        "보전조치": "Conservation Actions",
        "지정이력": "Designation History"
    }
    translated_sections = []
    for sec in sections:
        if sec["content"] is not None:
            translated_sections.append({
                "title": title_map.get(sec["title"], translate(sec["title"])),
                "content": translate(sec["content"])
            })
    return translated_sections
# Open the JSON file with UTF-8 encoding
with open('app/assets/species_info.json', 'r', encoding='utf-8') as file:
    data = json.load(file)
    # Recreate the translated dataset with full section translation
    translated_data_full = []
    for (index, item) in enumerate(data):
        translated_item = {
            "id": item["id"],
            "name": translate_name(item["korean_name"], item["english_name"]),
            "conservation_history": [translate(entry) for entry in item["conservation_history"]],
            "conservation_actions": [
                {
                    "action_type": translate_action_type(action["action_type"]),
                    "institutions": translate(action["institutions"])
                }
                for action in item["conservation_actions"]
            ],
            "extra_sections": translate_extra_sections_full(item["extra_sections"])
        }
        translated_data_full.append(translated_item)
        print(f"{index}/{len(data)} translated.")

# Save the fully translated result
output_path_full = "translated_species_info_full.json"
with open(output_path_full, "w", encoding="utf-8") as f:
    json.dump(translated_data_full, f, ensure_ascii=False, indent=2)